"""init

Revision ID: 3c1fc2ec7a2d
Revises: 
Create Date: 2022-03-17 12:02:38.483442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1fc2ec7a2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perumahan', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'perumahan', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perumahan', type_='foreignkey')
    op.drop_column('perumahan', 'user_id')
    # ### end Alembic commands ###
